#pragma once

#define LED1 							P1_1
#define LED2 							P1_0

#define MOTOR1 							P0_6
#define MOTOR1_TACHOMETER 				P2_7
#define MOTOR1_TACHOMETER_ERU_IRQ	 	ERU0_0_IRQn
#define MOTOR1_TACHOMETER_ERU_ETL	 	ERU0_ETL3
#define MOTOR1_TACHOMETER_ERU_OGU	 	ERU0_OGU0
#define MOTOR1_TACHOMETER_ERU_INPUT 	ERU0_ETL3_INPUTA_P2_7

#define MOTOR2 							P0_7
#define MOTOR2_TACHOMETER 				P2_10
#define MOTOR2_TACHOMETER_ERU_IRQ	 	ERU0_1_IRQn
#define MOTOR2_TACHOMETER_ERU_ETL	 	ERU0_ETL2
#define MOTOR2_TACHOMETER_ERU_OGU	 	ERU0_OGU1
#define MOTOR2_TACHOMETER_ERU_INPUT 	ERU0_ETL2_INPUTB_P2_10

#define MOTOR3_BRAKE P0_8

#define POT1 P2_6

#define BUTTON1 P2_9
#define BUTTON2 P2_10
#define BUTTON3 P2_11

#define MODULE_PTR CCU40
#define MODULE_NUMBER (0U)

#define SLICE0_PTR CCU40_CC40
#define SLICE0_NUMBER (0U)
#define SLICE0_OUTPUT MOTOR1

#define SLICE1_PTR CCU40_CC41
#define SLICE1_NUMBER (1U)
#define SLICE1_OUTPUT MOTOR2

#define TIMER_PERIOD 25000

#define SYSTICK_SHIFTER 16
#define SYSTICKS_PER_SECOND (1 << SYSTICK_SHIFTER)
#define SYSTICKS_PER_MINUTE (SYSTICKS_PER_SECOND * 60)

#define MAX_RPM 24000
