#pragma once

#define LED_RED 						P1_1
#define LED_ORANGE 						P1_0
#define LED_YELLOW						P0_15
#define LED_GREEN						P0_14

#define MOTOR1 							P0_6
#define MOTOR1_TACHOMETER 				P2_7

#define MOTOR2 							P0_7
#define MOTOR2_TACHOMETER 				P2_10

#define MOTOR3 P0_8
#define MOTOR3_BRAKE P0_9

#define POT1 P2_6
#define BATT_SENSE P2_9

#define BUTTON1 P0_5
#define BUTTON2 P2_0
#define BUTTON3 P2_11

#define LIGHT_BARRIER1 P0_0

#define MODULE_PTR CCU40
#define MODULE_NUMBER (0U)

#define SLICE0_PTR CCU40_CC40
#define SLICE0_NUMBER (0U)
#define SLICE0_OUTPUT MOTOR1

#define SLICE1_PTR CCU40_CC41
#define SLICE1_NUMBER (1U)
#define SLICE1_OUTPUT MOTOR2

#define SLICE2_PTR CCU40_CC42
#define SLICE2_NUMBER (2U)
#define SLICE2_OUTPUT MOTOR3

#define TIMER_PERIOD 25000

#define SYSTICK_SHIFTER 16
#define SYSTICKS_PER_SECOND (1 << SYSTICK_SHIFTER)
#define SYSTICKS_PER_MINUTE (SYSTICKS_PER_SECOND * 60)

#define MIN_RPM 6000
#define MAX_RPM 28000
#define PUSHER_POWER_SINGLE 0.4
#define PUSHER_POWER_FULL 0.6
#define PUSHER_POWER_RETURN 0.3

#define BATTERY_LOW_COUNTER_LIMIT 5000
#define BATTERY_LOW_THRESHOLD 620
